version: '3.7'
services:  
  mysqldb:    
    image: mysql:8.0.19
    container_name: aqa4-sql
    ports:      
      - '3306:3306'    
    volumes:      
      - ./mysqldb:/var/lib/mysql/
      - ./dbini:/docker-entrypoint-initdb.d/
    environment:      
      - MYSQL_RANDOM_ROOT_PASSWORD=yes      
      - MYSQL_DATABASE=vera      
      - MYSQL_USER=vera
      - MYSQL_PASSWORD=pass
      